const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const sentimentsList=['Positif','Négatif','Neutre','Mixte','Indéterminé','Sans texte'];
const defaultThemes={
'Livraison':['livraison','livreur','livré','colis','retard','delivery','shipping','delivered','package','late','entrega','entregue','frete','transportadora','atraso','atrasado','correios'],
'Produit / qualité':['produit','qualité','cassé','défectueux','taille','couleur','product','quality','broken','size','color','produto','qualidade','quebrado','defeito','tamanho','cor'],
'Prix / paiement':['prix','cher','paiement','remboursement','price','expensive','payment','refund','preço','caro','pagamento','reembolso','valor'],
'Service client':['sav','assistance','service','support','vendeur','seller','atendimento','vendedor','contato','resposta'],
'Emballage':['emballage','emballé','packaging','packed','embalagem','embalado','caixa']};
let records=[],columns=[],rows=[],filtered=[],page=0,filename='avis',busy=false,selectedFile=null,stopRequested=false,themeRules=defaultThemes,expected=0;
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'ok'}
function lock(value){busy=value;['file','demo','analyze','reimport','sheet','engine','scope','customthemes','textcol','titlecol','ratingcol','export','json'].forEach(id=>$(id).disabled=value)}
async function api(path,body,headers={}){const response=await fetch(path,{method:'POST',headers,body});const data=await response.json();if(!response.ok)throw Error(data.error||'Erreur de traitement');return data}
function guess(id,candidates,required=false){const name=candidates.find(c=>columns.some(x=>norm(x)===c));$(id).innerHTML='<option value="">'+(required?'Choisir la colonne…':'Aucune')+'</option>'+columns.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$(id).value=columns.find(x=>norm(x)===name)||''}
function importOptions(){return {delimiter:$('delimiter').value==='tab'?'\t':$('delimiter').value,encoding:$('encoding').value,text_mode:$('textmode').value,header:$('header').checked,sheet:$('sheet').value}}
async function load(file,keepSheet=false){if(busy)return;lock(true);status('Chargement du fichier…');$('mapping').hidden=true;$('results').hidden=true;$('analysisstatus').textContent='';records=[];rows=[];expected=0;if(!keepSheet)$('sheet').value='';try{
 let data;if(file){if(file.size>100*1024*1024)throw Error('Le fichier dépasse 100 Mo.');filename=file.name;selectedFile=file;data=await api('/api/import',file,{'X-Filename':encodeURIComponent(file.name),'X-Options':encodeURIComponent(JSON.stringify(importOptions())),'Content-Type':'application/octet-stream'})}else{selectedFile=null;filename='olist_order_reviews_dataset.csv';data=await api('/api/demo','')}
 records=data.records;columns=data.columns;const chosen=$('sheet').value;$('sheet').innerHTML=(data.sheets||[]).map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');if(chosen&&data.sheets.includes(chosen))$('sheet').value=chosen;$('sheetbox').hidden=!data.sheets.length;
 $('info').textContent=data.info;guess('textcol',['review_comment_message','commentaire','comment','review','text','texte','avis','message','content','review_text','comentario'],true);guess('titlecol',['review_comment_title','titre','title']);guess('ratingcol',['review_score','rating','score','note','stars','etoiles']);
 $('preview').innerHTML='<table><thead><tr>'+columns.map(c=>'<th>'+esc(c)+'</th>').join('')+'</tr></thead><tbody>'+records.slice(0,5).map(r=>'<tr>'+columns.map(c=>'<td>'+esc(String(r[c]).slice(0,400))+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
 $('mapping').hidden=false;status(`${records.length.toLocaleString('fr-FR')} avis chargés · ${filename}. Vérifie les colonnes et l’aperçu.`);
 }catch(e){$('sheetbox').hidden=true;status(e.message,true)}finally{lock(false)}}
function getThemes(){const rules={};for(const line of $('customthemes').value.split('\n')){if(!line.trim())continue;const i=line.indexOf('=');if(i<1)throw Error('Thèmes : utilise Nom = mot, expression');const name=line.slice(0,i).trim(),terms=line.slice(i+1).split(',').map(t=>t.trim()).filter(Boolean);if(!terms.length)throw Error(`Le thème « ${name} » n’a aucun mot-clé.`);if(rules[name])throw Error('Deux thèmes portent le même nom.');rules[name]=terms}return rules}
function updateThemes(){const current=$('theme').value;$('theme').innerHTML='<option value="">Tous</option>'+Object.keys(themeRules).map(t=>`<option>${esc(t)}</option>`).join('')+'<option>Sans thème détecté</option>';$('theme').value=current}
function duplicates(){const counts=new Map();for(const r of rows){const k=norm(r.text).replace(/\s+/g,' ').trim();if(k)counts.set(k,(counts.get(k)||0)+1)}for(const r of rows)r.duplicate=(counts.get(norm(r.text).replace(/\s+/g,' ').trim())||0)>1}
async function run(){if(busy)return;if(!$('textcol').value){status('Choisis une colonne de commentaires.',true);return}try{themeRules=getThemes()}catch(e){status(e.message,true);return}lock(true);status('Analyse en cours…');$('cancel').disabled=false;stopRequested=false;rows=[];filtered=[];updateThemes();$('results').hidden=true;const limit=$('scope').value==='all'?records.length:Math.min(Number($('scope').value),records.length);expected=limit;const mapping={text:$('textcol').value,title:$('titlecol').value,rating:$('ratingcol').value,engine:$('engine').value,themes:themeRules};let failed=false;const start=Date.now();
 try{for(let offset=0;offset<limit&&!stopRequested;offset+=64){const end=Math.min(offset+64,limit);$('analysisstatus').textContent=`Analyse ${offset.toLocaleString('fr-FR')} / ${limit.toLocaleString('fr-FR')} · lot en cours…`;
  const data=await api('/api/analyze',JSON.stringify({records:records.slice(offset,end),mapping}),{'Content-Type':'application/json'});rows.push(...data.rows.map((r,i)=>({...r,index:offset+i+1,originalSentiment:r.sentiment})));$('progress').value=100*rows.length/limit;
  $('analysisstatus').textContent=`${rows.length.toLocaleString('fr-FR')} / ${limit.toLocaleString('fr-FR')} avis · ${Math.round((Date.now()-start)/1000)} s`;
 }}catch(e){failed=true;status(`Analyse interrompue : ${e.message} Les résultats déjà calculés sont conservés.`,true)}finally{duplicates();reset();$('results').hidden=false;lock(false);$('cancel').disabled=true;$('coverage').hidden=rows.length===records.length;$('coverage').textContent=`Périmètre partiel : ${rows.length.toLocaleString('fr-FR')} avis analysés sur ${records.length.toLocaleString('fr-FR')} importés. Les graphiques et exports portent uniquement sur ces avis.`;if(!failed)status(stopRequested?'Analyse arrêtée. Résultats partiels disponibles.':'Analyse terminée. Résultats disponibles.');$('analysisstatus').textContent=`${rows.length.toLocaleString('fr-FR')} avis analysés sur ${limit.toLocaleString('fr-FR')} demandés · ${Math.round((Date.now()-start)/1000)} s`;}}
function reset(){['search','sentiment','theme','min','max'].forEach(id=>$(id).value='');['duplicates','uncertain','corrected','conflict'].forEach(id=>$(id).checked=false);$('sort').value='original';apply()}
function conflict(r){const scale=Number($('scale').value);if(!scale||r.rating===null)return false;const min=scale===5?1:0;if(r.rating<min||r.rating>scale)return false;const value=(r.rating-min)/(scale-min);return (value<=.25&&r.sentiment==='Positif')||(value>=.75&&r.sentiment==='Négatif')}
function apply(){const q=norm($('search').value),sent=$('sentiment').value,theme=$('theme').value,min=$('min').value,max=$('max').value;filtered=rows.filter(r=>(!q||norm(r.text).includes(q))&&(!sent||r.sentiment===sent)&&(!theme||(theme==='Sans thème détecté'?!r.themes.length:r.themes.includes(theme)))&&(!$('duplicates').checked||r.duplicate)&&(!$('uncertain').checked||r.uncertain)&&(!$('corrected').checked||r.corrected)&&(!$('conflict').checked||conflict(r))&&(min===''||(r.rating!==null&&r.rating>=Number(min)))&&(max===''||(r.rating!==null&&r.rating<=Number(max))));const sort=$('sort').value;if(sort==='long')filtered.sort((a,b)=>b.text.length-a.text.length);if(sort==='low'||sort==='high')filtered.sort((a,b)=>a.rating===null?(b.rating===null?0:1):b.rating===null?-1:(a.rating-b.rating)*(sort==='low'?1:-1));page=0;draw()}
function bars(id,entries,total=filtered.length){
 const layout='grid-template-columns:125px minmax(40px,1fr) 105px';
 const base=total?`Base : ${total.toLocaleString('fr-FR')} avis sélectionnés, y compris les avis sans texte.`:'Aucun avis sélectionné.';
 const note=id==='themes'?'Un avis peut compter dans plusieurs thèmes, ou dans aucun : les pourcentages ne totalisent pas nécessairement 100 %.':'Chaque avis appartient à une seule catégorie ; les pourcentages totalisent 100 % avant arrondi.';
 $(id).innerHTML=`<p class="muted"><small>${base}</small></p><div class="barrow" style="${layout}" aria-hidden="true"><span></span><div style="display:flex;justify-content:space-between;color:#5b736d;font-size:11px"><span>0 %</span><span>50 %</span><span>100 %</span></div><span>Effectif · part</span></div>`+entries.map(([name,n])=>{
  const percentage=total?n/total*100:0, label=percentage.toLocaleString('fr-FR',{maximumFractionDigits:1})+' %';
  return `<div class="barrow" style="${layout}"><span>${esc(name)}</span><div class="track" role="img" aria-label="${esc(name)} : ${n} sur ${total} avis, ${label}"><div class="bar ${name==='Négatif'?'negative':name==='Indéterminé'||name==='Sans texte'?'unknown':''}" style="width:${percentage}%"></div></div><span>${n.toLocaleString('fr-FR')} · ${label}</span></div>`;
 }).join('')+`<p class="muted"><small>${note}</small></p>`;
}
function draw(){const sentiments=sentimentsList.map(x=>[x,0]),themes=Object.keys(themeRules).map(x=>[x,0]);let sum=0,n=0;for(const r of filtered){const s=sentiments.find(x=>x[0]===r.sentiment);if(s)s[1]++;for(const t of r.themes){const target=themes.find(x=>x[0]===t);if(target)target[1]++}if(r.rating!==null){sum+=r.rating;n++}}$('total').textContent=filtered.length.toLocaleString('fr-FR');$('negative').textContent=sentiments.find(x=>x[0]==='Négatif')[1].toLocaleString('fr-FR');$('empty').textContent=sentiments.find(x=>x[0]==='Sans texte')[1].toLocaleString('fr-FR');$('mean').textContent=n?(sum/n).toLocaleString('fr-FR',{maximumFractionDigits:2}):'—';bars('sentiments',sentiments);bars('themes',themes);$('resultcount').textContent=`${filtered.length.toLocaleString('fr-FR')} sur ${rows.length.toLocaleString('fr-FR')} avis analysés · 50 par page`;
 $('body').innerHTML=filtered.slice(page*50,(page+1)*50).map(r=>`<tr><td>${r.index}</td><td class="comment">${esc(r.text)||'<em>Sans commentaire</em>'}${r.duplicate?'<br><span class="badge">Texte répété</span>':''}${conflict(r)?'<br><span class="badge negative">Note contradictoire</span>':''}</td><td>${r.rating===null?'—':esc(r.rating)}</td><td><label class="muted" for="fix-${r.index}">${r.corrected?'Corrigé manuellement':r.uncertain?'À vérifier':'Classement automatique'}</label><select id="fix-${r.index}" data-index="${r.index}" aria-label="Corriger le sentiment de l’avis ${r.index}">${sentimentsList.map(s=>`<option${r.sentiment===s?' selected':''}>${esc(s)}</option>`).join('')}</select><small>${r.confidence==null?'Sans score de modèle':`Score du modèle : ${Math.round(r.confidence*100)} %`}</small></td><td>${r.themes.map(t=>`<span class="badge">${esc(t)}</span>`).join('')||'—'}</td><td><details><summary>Source et méthode</summary><p>${esc(r.method)}</p>${r.originalSentiment?`<p>Sentiment initial : ${esc(r.originalSentiment)}</p>`:''}<p>${r.probabilities?'Scores : '+esc(JSON.stringify(r.probabilities)):'Mots repérés : '+(esc(r.evidence.join(', '))||'aucun')}</p>${r.chunks>1?`<p>${r.chunks} segments lus, aucun tronqué.</p>`:''}<pre>${esc(JSON.stringify(r.source,null,2))}</pre></details></td></tr>`).join('')||'<tr><td colspan="6">Aucun avis ne correspond à ces filtres.</td></tr>';$('page').textContent=`Page ${page+1} / ${Math.max(1,Math.ceil(filtered.length/50))}`;$('prev').disabled=page===0;$('next').disabled=(page+1)*50>=filtered.length}
async function download(content,type,ext){$('export').disabled=true;$('json').disabled=true;try{const result=await api('/api/export',JSON.stringify({content,format:ext,name:filename}),{'Content-Type':'application/json'});$('downloadlink').href=result.url;$('downloadlink').download=result.filename;$('downloadlink').textContent='Télécharger '+result.filename;$('downloadbox').hidden=false;status('Export créé. Une copie est conservée dans le dossier exports de l’outil.');$('downloadlink').click()}catch(e){status('Export impossible : '+e.message,true)}finally{$('export').disabled=false;$('json').disabled=false}}
function annotation(r){return {sentiment:r.sentiment,sentiment_initial:r.originalSentiment||r.sentiment,score_modele:r.confidence??null,a_verifier:!!r.uncertain,correction_manuelle:!!r.corrected,themes:r.themes,indices:r.evidence,texte_repete:r.duplicate,methode:r.method,avis_analyses:rows.length,avis_importes:records.length}}
$('json').onclick=()=>{clearTimeout(timer);apply();download(JSON.stringify(filtered.map(r=>({source:r.source,analyse:annotation(r)})),null,2),'application/json','json')};
$('export').onclick=()=>{clearTimeout(timer);apply();const keys=['sentiment','sentiment_initial','score_modele','a_verifier','correction_manuelle','themes','indices','texte_repete','methode','avis_analyses','avis_importes'];const extra=keys.map(key=>{let name='analyse_'+key;while(columns.includes(name))name='_'+name;return name});const cell=value=>'"'+String(value??'').replace(/^[\s]*[=+@\-]/,s=>"'"+s).replace(/"/g,'""')+'"';const lines=[[...columns,...extra],...filtered.map(r=>{const a=annotation(r);return [...columns.map(c=>r.source[c]),...keys.map(k=>Array.isArray(a[k])?a[k].join(' | '):a[k])]})];download('\ufeff'+lines.map(row=>row.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8','csv')};
let timer;['search','min','max'].forEach(id=>$(id).oninput=()=>{clearTimeout(timer);timer=setTimeout(apply,200)});['sentiment','theme','duplicates','sort','uncertain','corrected','conflict','scale'].forEach(id=>$(id).onchange=apply);
$('body').onchange=e=>{const index=Number(e.target.dataset.index);const row=rows.find(r=>r.index===index);if(!row)return;row.originalSentiment??=row.sentiment;row.sentiment=e.target.value;row.corrected=true;row.uncertain=false;apply()};
$('reset').onclick=reset;$('prev').onclick=()=>{page--;draw()};$('next').onclick=()=>{page++;draw()};$('analyze').onclick=run;$('cancel').onclick=()=>{stopRequested=true;$('cancel').disabled=true;$('analysisstatus').textContent='Arrêt demandé : fin du lot en cours…'};
$('file').onchange=e=>{if(e.target.files[0])load(e.target.files[0])};$('demo').onclick=()=>load();$('reimport').onclick=()=>load(selectedFile,true);$('sheet').onchange=()=>load(selectedFile,true);
$('customthemes').value=Object.entries(defaultThemes).map(([name,terms])=>`${name} = ${terms.join(', ')}`).join('\n');
async function modelStatus(){try{const config=await (await fetch('/api/config')).json();$('modelstatus').textContent=config.local_model?'Modèle installé · exécution hors ligne':'Modèle absent : exécuter download_model.py';if(!config.local_model)$('engine').value='rules'}catch(e){$('modelstatus').textContent='Serveur inaccessible'}}
modelStatus();
$('closedownload').onclick=()=>{$('downloadbox').hidden=true};
